apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.1
          envFrom:
            - configMapRef:
                name: wagtail-config
            - secretRef:
                name: wagtaildemo-secrets
          env:
            - name: POSTGRES_DB
              value: app_db
            - name: POSTGRES_USER
              value: app_user
            - name: POSTGRES_PASSWORD
              value: changeme
          ports:
            - containerPort: 5432
