apiVersion: v1
kind: Service
metadata:
  name: bakerydemo-postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: bakerydemo-redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: bakerydemo-app-service
  labels:
    app: app
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
